name: Clean Storybook Deployments
on:
  pull_request:
    types: [closed]

jobs:
  remove_pull_request: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Delete the pull request directory
        run: |
          git config --global user.email "bot@bot.bot"
          git config --global user.name "Storybook Deployer"
          git rm -rf ./storybook/pull_requests/${PULL_REQUEST_NUMBER}
          git commit -m "Removes pull_requests/${PULL_REQUEST_NUMBER} storybook deployments"
          git push origin gh-pages
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}