name: CI

# How to create a clean gh-pages branch
# git symbolic-ref HEAD refs/heads/gh-pages
# rm .git/index
# git clean -fdx
# echo "My Site Name" > index.html
# mkdir -p ./storybook/pull_requests
# echo "Storybooks on Pull Requests" > ./storybook/pull_requests/index.html
# mkdir -p ./storybook/main
# echo "Storybooks on Main" > ./storybook/main/index.html
# git add .
# git commit -a -m "Set up gh-pages from scratch for Storybook Deployment"
# git push origin gh-pages

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  delete: 
    if: ${{github.event.pull_request.action == 'closed'}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Delete the branch directory
        run: |
          echo A pull request just closed. Time to clean up the storybook deployment.
          git switch gh-pages
          git rm -rf ./storybook/pull_request/${GITHUB_REF##*/}
          git commit -m "Remove pull_request/${GITHUB_REF##*/} storybook deployment."
          git push origin gh-pages

  build:
    if: ${{github.event.pull_request.action != 'closed'}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Dependencies and Build
        run: |
          npm install
          npm run build-storybook

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -b gh-pages -d storybook/pull_request/${GITHUB_REF##*/${GITHUB_SHA}/} /storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}